# Form implementation generated from reading ui file 'coffeeMike.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_coffeeMike(object):
    def setupUi(self, coffeeMike):
        coffeeMike.setObjectName("coffeeMike")
        coffeeMike.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=coffeeMike)
        self.centralwidget.setObjectName("centralwidget")
        self.lblStore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStore.setGeometry(QtCore.QRect(320, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.lblStore.setFont(font)
        self.lblStore.setObjectName("lblStore")
        self.txtLattes = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLattes.setGeometry(QtCore.QRect(390, 150, 113, 22))
        self.txtLattes.setObjectName("txtLattes")
        self.txtCappuccinos = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCappuccinos.setGeometry(QtCore.QRect(390, 190, 113, 22))
        self.txtCappuccinos.setObjectName("txtCappuccinos")
        self.txtEspressos = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtEspressos.setGeometry(QtCore.QRect(390, 230, 113, 22))
        self.txtEspressos.setObjectName("txtEspressos")
        self.txtSize = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSize.setGeometry(QtCore.QRect(390, 270, 113, 22))
        self.txtSize.setObjectName("txtSize")
        self.lblLattes = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLattes.setGeometry(QtCore.QRect(190, 150, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.lblLattes.setFont(font)
        self.lblLattes.setObjectName("lblLattes")
        self.lblCappuccinos = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCappuccinos.setGeometry(QtCore.QRect(190, 190, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.lblCappuccinos.setFont(font)
        self.lblCappuccinos.setObjectName("lblCappuccinos")
        self.lblEspressos = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblEspressos.setGeometry(QtCore.QRect(190, 230, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.lblEspressos.setFont(font)
        self.lblEspressos.setObjectName("lblEspressos")
        self.lblSize = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblSize.setGeometry(QtCore.QRect(240, 270, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.lblSize.setFont(font)
        self.lblSize.setObjectName("lblSize")
        self.btnOrder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnOrder.setGeometry(QtCore.QRect(300, 310, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.btnOrder.setFont(font)
        self.btnOrder.setObjectName("btnOrder")
        self.priceLattes = QtWidgets.QLabel(parent=self.centralwidget)
        self.priceLattes.setGeometry(QtCore.QRect(520, 150, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.priceLattes.setFont(font)
        self.priceLattes.setObjectName("priceLattes")
        self.priceCappuccinos = QtWidgets.QLabel(parent=self.centralwidget)
        self.priceCappuccinos.setGeometry(QtCore.QRect(520, 190, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.priceCappuccinos.setFont(font)
        self.priceCappuccinos.setObjectName("priceCappuccinos")
        self.priceEspressos = QtWidgets.QLabel(parent=self.centralwidget)
        self.priceEspressos.setGeometry(QtCore.QRect(520, 230, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.priceEspressos.setFont(font)
        self.priceEspressos.setObjectName("priceEspressos")
        self.txtTotal = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotal.setGeometry(QtCore.QRect(282, 360, 131, 21))
        self.txtTotal.setReadOnly(True)
        self.txtTotal.setObjectName("txtTotal")
        self.smallLarge = QtWidgets.QLabel(parent=self.centralwidget)
        self.smallLarge.setGeometry(QtCore.QRect(530, 270, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.smallLarge.setFont(font)
        self.smallLarge.setObjectName("smallLarge")
        coffeeMike.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=coffeeMike)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        coffeeMike.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=coffeeMike)
        self.statusbar.setObjectName("statusbar")
        coffeeMike.setStatusBar(self.statusbar)

        self.retranslateUi(coffeeMike)
        QtCore.QMetaObject.connectSlotsByName(coffeeMike)
        
        self.btnOrder.clicked.connect(self.coffee_store)
            
        
    def coffee_store(self):
        # get input value entered by user and store in variables       
        lattes_number = self.txtLattes.text()
        cappuccinos_number = self.txtCappuccinos.text()
        espressos_number = self.txtEspressos.text()
        #converts string input into integer input       
        if  lattes_number == "":
            lattes_number = "0"
        if cappuccinos_number == "":
            cappuccinos_number = "0"
        if espressos_number == "":
            espressos_number = "0"
        if lattes_number.isdigit() and cappuccinos_number.isdigit() and espressos_number.isdigit():
            lattes_total = int(lattes_number)
            cappuccinos_total = int(cappuccinos_number)
            espressos_total = int(espressos_number)
            # Calculates Order total
            total_order = 0
            lattes_price = 4.50
            cappuccinos_price = 5.00
            espresso_price = 5.50
            if lattes_total > 0:
                total_order += lattes_total * lattes_price
            if cappuccinos_total > 0:
                total_order += cappuccinos_total * cappuccinos_price
            if espressos_total >0:
                total_order += espressos_total * espresso_price
            # Input validation to make sure user inputs either small or large          
            cup_size = self.txtSize.text().strip().lower()
            if cup_size != 'small' and cup_size != 'large':
                msg = QMessageBox()
                msg.setText('Please enter either small or large')
                msg.exec()
                return
            # Includes a $2 fee if cup size is large
            if cup_size == 'large':
                total_order += 2
            # Sets the order total   
            self.txtTotal.setText(str(total_order))
        # Erorr message if value entered is not an integer  
        else:
            msg = QMessageBox()
            msg.setText("Please enter a number not words")
            msg.exec()   
            return

    def retranslateUi(self, coffeeMike):
        _translate = QtCore.QCoreApplication.translate
        coffeeMike.setWindowTitle(_translate("coffeeMike", "Coffee Mike"))
        self.lblStore.setText(_translate("coffeeMike", "Coffee Mike"))
        self.lblLattes.setText(_translate("coffeeMike", "Number of Lattes"))
        self.lblCappuccinos.setText(_translate("coffeeMike", "Number of Cappuccinos"))
        self.lblEspressos.setText(_translate("coffeeMike", "Number of Espressos"))
        self.lblSize.setText(_translate("coffeeMike", "Size"))
        self.btnOrder.setText(_translate("coffeeMike", "Order"))
        self.priceLattes.setText(_translate("coffeeMike", "Latte: $4.50"))
        self.priceCappuccinos.setText(_translate("coffeeMike", "Cappuccinos: $5.00"))
        self.priceEspressos.setText(_translate("coffeeMike", "Espressos: $5.50"))
        self.smallLarge.setText(_translate("coffeeMike", "Small/Large"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    coffeeMike = QtWidgets.QMainWindow()
    ui = Ui_coffeeMike()
    ui.setupUi(coffeeMike)
    coffeeMike.show()
    sys.exit(app.exec())
